devtools::install_version("dplyr", "0.5.0")
devtools::install_github("joshuaulrich/quantmod")
devtools::install_version("zoo", "1.7-14")
devtools::install_version("xts", "0.9-7")
devtools::install_version("TTR", "0.23-1")
devtools::install_version("MUCflights", "0.0-3")
devtools::install_version("ggplot2", "2.1.0")
devtools::install_version("plotly", "4.5.2")
